apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac11950-inference
  labels:
    app: mnist-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-inference
  template:
    metadata:
      labels:
        app: mnist-inference
    spec:
      containers:
      - name: inference-container
        image: abhishekchigurupati/inferencegcp:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: mnist-model-volume
          mountPath: /mnt
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: mnist-model-volume
        persistentVolumeClaim:
          claimName: ac11950-model-pvc
